version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: outlaytrackuser
      POSTGRES_PASSWORD: q
      POSTGRES_DB: outlaytrackdb
    networks:
      - outlaytrack
networks:
  outlaytrack: